[package]
name = "pdf2pwg"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "^1", features = ["attributes", "unstable"] }
image = "0.24.6"
pdfium-render = { version = "^0.8" }
